name: build

on:
  push:
  pull_request:

env:
  # USE UTF8 ENCODING. SHOULD BE DEFAULT, BUT THIS IS INSURANCE AGAINST FUTURE CHANGES
  PYTHONIOENCODING: UTF8

jobs:
  build:
    name: build
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
    defaults:
      run:
        shell: bash -l {0}

    steps:
      - name: checkout code
        uses: actions/checkout@d632683dd7b4114ad314bca15554477dd762a938  # v4.2.0

      - name: install conda
        uses: conda-incubator/setup-miniconda@a4260408e20b96e80095f42ff7f1a15b27dd94ca  # v3.0.4
        with:
          auto-update-conda: true
          python-version: '3.7'
          channels: http://ssb.stsci.edu/astroconda,astropy-ci-extras

      - name: install dependencies
        run: |
          pip install 'astropy<5' crds matplotlib scipy stistools
          pip install nose

      - name: run build
        run: |
          python setup.py install

      - name: run tests
        run: |
          nosetests
